apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-task-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source:
    repoURL: 'https://github.com/konbusalov/ArgoCD_Task_Helm_Repo.git'
    targetRevision: main
    path: argocd-task-chart/
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kuber
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true